name: word redis deploy
on:
  workflow_dispatch:

jobs:
  create-redis-conf:
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        uses: actions/checkout@v4
      - name: create redisconf
        run: |
          echo "requirepass redispassword123" > redis.conf
          cat redis.conf
      - name: dockerfile build
        run: |
          docker build \
           -f ./dockerfile.wordRedis \
           -t redis-word-imaged \
           .
      # - name: Upload config
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: redis-config
      #     path: redis.conf
    #   - name: docker Build
    #     run: |
    #       docker build \
    #         -f ./dockerfile.wordRedis
    #         -t redis-word-image
  run-docker-image:
    runs-on: ubuntu-latest
    needs: create-redis-conf
    steps:
      # - uses: actions/checkout@v4
      # - name: Download config
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: redis-config
      # - name: check file
      #   run: cat $(pwd)/redis.conf
      - name: docker Build
        run: |
          docker run -d \
            --name worker-redis \
            -p 6381:6379 \
            -e REDIS_PASSWORD="redispassword124" \
            -v redis_data:/data \
            --restart always \
            --health-cmd="redis-cli -a \$REDIS_PASSWORD ping" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=3 \
            --health-start-period=30s \
            redis-word-imaged